### ISSUE TITLE
daysBetween program rules

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#33] opened 2018-03-03 18:34 UTC
This program rule is well formed but the action is not triggered in the eRegistry. The message only appears if the first date of the argument is the same as the second date of the argument. Something to do with the new date format, perhaps?

![image](https://user-images.githubusercontent.com/36451485/36937845-99784126-1f19-11e8-992d-5f63c2afbcff.png)

![image](https://user-images.githubusercontent.com/36451485/36937879-16eba346-1f1a-11e8-9119-d0fcbb75a046.png)

However the action DOES take place correctly in the Tracker Capture app.
![image](https://user-images.githubusercontent.com/36451485/36937877-064bec1c-1f1a-11e8-837e-f757a75126e0.png)

**Comment by lukasewvd** [comment] 2018-03-05 12:05
@iambodo can you test this again? For me this is working as intended.

**Comment by lukasewvd** [comment] 2018-03-08 08:28
Closing the issue, tell us if you are still experiencing this issue.

**Closed by lukasewvd** 2018-03-08 08:28 UTC
