### ISSUE TITLE
Server error when trying to edit Previous pregnancy stage

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#58] opened 2018-03-27 09:34 UTC
After completing a previous pregnancy stage, when you try to edit it immediately, you get the Server error below. I have not seen it in another stage yet. And this did not use to happen previously

![image](https://user-images.githubusercontent.com/36447512/37959126-b3d0b8f4-31b2-11e8-92e9-88a44cf9a24f.png)

**Comment by lukasewvd** [comment] 2018-03-27 11:51
@AkubaD I am not able to reproduce this issue. Could you clean cache and try again?

**Comment by lukasewvd** [comment] 2018-04-03 11:23
@AkubaD @RahmanMonjur Okay, closing this issue. If you still have problems with this tell me and I will re-open the issue.

**Closed by lukasewvd** 2018-04-03 11:23 UTC
