### ISSUE TITLE
Search gives list of all clients and does not restrict to limit of max of 5 results

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#9] opened 2018-02-14 11:29 UTC
This used to be configured for eRegistries:
Search using village = Bakra returns over 50 results. We previously limited search results to max of 5 results. Anything above that would give request to enter more parameters to limit the search

**Comment by zepto5** [comment] 2018-02-14 12:15
In 2.29, it is possible to configure this for each program. 
Go to Maintenance app, then programs and select a program.
Set "Maximum number of tracked entity instances to return in search" to 5.

I think this will only work for non-superusers. For superuser, I think a search will return all matches.

**Comment by AkubaD** [comment] 2018-02-14 12:23
Thanks for the directions. I followed them and set to limit of 5 for MCH program. For initial search, it briefly gave a pop up saying results were above the limit, but then it gave the full over 50 results list a second later. All subsequent searches gave the full results list without the brief appearance of the pop-up

**Comment by zepto5** [comment] 2018-02-14 12:34
What user are you using?

**Comment by AkubaD** [comment] 2018-02-14 12:55
admin user. Sorry, you did say it wont work for non-superusers, right? But currently, only superusers have any program access, so I can't test with non-supersusers. Once non-superusers have access, I will test and give feedback. Can you reopen this ticket until then?

**Comment by zepto5** [comment] 2018-02-14 15:40
Yes. 
So for superusers (admin), searching will return all found clients.

For any non-superuser: Returns maximum 5 clients. If more clients is found, user will get a pop-up message requesting more parameters.

**Comment by iambodo** [comment] 2018-03-01 12:24
this restriction also does not work for non-superusers. 
can still see more than five clients in the eRegistry app.
what is the specific authority that gives access to the full list of TEI? so we can make sure our "non-SUs" do not have that permission.

**Comment by zepto5** [comment] 2018-03-01 13:33
Make sure that the user does not have the authority ALL.
Also, try removing these authorities:
Search Tracked Entity Instances
Search Tracked Entity Instances In All Org Units

**Comment by iambodo** [comment] 2018-03-01 14:49
Our non-superusers do not have the ALL authority.
We need our non-super users to have both of these authorities:

- Search Tracked Entity Instances
- Search Tracked Entity Instances In All Org Units

Otherwise those users will not be able to search and find TEI in the e-Registry app. Especially those that were registered outside the org unit.

**Comment by zepto5** [comment] 2018-03-02 09:03
Hey. 
Could you install the latest war? I can get this working on the dhis dev instance, but not the bd-eregistry instance. 

These authorities is not used any more. Searchable org units needs to be set per user. The users with the "Search tracked entity instances in all org units" should then be assigned with the root org unit. We may have to make an upgrade script for this.

**Comment by iambodo** [comment] 2018-03-05 05:59
We have updated to latest WAR file. Could you please clarify then how maximum search results are set by user group, user role, or user? These two statements seem to conflict.

> 1) "So for superusers (admin), searching will return all found clients."

> 2) "These authorities is not used any more. Searchable org units needs to be set per user. The users with the "Search tracked entity instances in all org units" should then be assigned with the root org unit. "

_Are you saying that "superusers (admin)" users need to be assigned to the root org unit for searching?_ 

**Example test:** I have reset the "tracker data capture" user role so it does not include any search tracked entity permissions. https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance-user/showUpdateRoleForm.action?id=645821

**FWV1** has access to MCH program user group and the tracker data capture user role. But she can still see more than 5 TEI in search results (search "test" in full name on the e-Registry app).
https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance-user/showUpdateUserForm.action?id=637276 No errors in client log.
![image](https://user-images.githubusercontent.com/36451485/36959505-b6172098-2042-11e8-8c76-8399ff5edf19.png)




The MCH program is set to only four search results.
https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance/#/edit/programSection/program/WSGAb5XwJ3Y

CC: @Bekkalizer

**Comment by zepto5** [comment] 2018-03-05 08:29
If a user has the authority "ALL", all clients found will be returned from the search.

This is clearly a bug. I will try to reproduce this locally, and debug to see whats happening.

**Comment by zepto5** [comment] 2018-03-05 14:03
For TWV1:
Data capture org units:
Matlab North
Matlab South

Search org units:
Matlab North
Matlab South

Searching will search for clients in org units defined in the users "search organisation units". If the "search org units" is the same as "data capture org unit", I guess it will return all clients, because it will be considered a local search (searching in own org units).

Could you try set the user "TWV1" search organisation units to the root organisation unit only (Bangladesh)? It should then search in all org units. Since TWV1 only has data capture org units set to Matlab South/North, the limit should kick in. 
This can be done in the user maintenance by clicking a user, and then select "Assign search organisation units"

**Comment by iambodo** [comment] 2018-03-05 15:15
I made the requested change and all search resutls are still showing up for FWV1

I'm not sure why highest data capture org unit needs to be a child of the highest search org units for the "maximum search results returned" feature to kick in. The max search results is set through the program, not the user, Even if a "local search" of a user's own org unit returns more than five possible clients, the behavior should be the same, The box should ask for more restrictive search parameters.

![image](https://user-images.githubusercontent.com/36451485/36982188-874d0000-208f-11e8-9a2d-71da4a608e36.png)

**Comment by zepto5** [comment] 2018-03-05 16:31
The "Assign search organisation units" have some weird behaviour as it keeps reseting the search org units. I have created an issue for the User App developers.  Should work for FWV1 now, but you would need to reset the password.

"maximum search results returned":
Yes, this is set on the program. But it is only triggered when searching outside the users data capture organisation units.

If you also want to restrict the "local search", I can make a fix for that.

**Comment by zepto5** [comment] 2018-03-07 15:21
Quoting Markus:
"The search org unit represents the org unit tree that the user should be able to find records in. Should be set to Bangladesh for all users. The data capture orgunit is the orgunit that the user has every access to see and capture data for"

When a users search org units = data capture org units, the search mechanism will see this as a search with no restrictions. This is because the user already has every access to see and capture data in these org units. The search result will only be clients from your own organisation units. This is called a "local search".

When setting the search org unit to Bangladesh, or any other org unit than the data capture org units, the restrictions will apply. When searching, you are now trying to find clients in any org unit, including org units you cannot see or capture data for.

Anyways, I made a fix that forces the restrictions to apply, even when considered a "local search" in commit 3e46cb0.

But you will have to set search org unit to Bangladesh for all users anyway, or the search will only return results from the data capture org units.

Please install the latest war. Should fix some issues when assigning search organisation units.

**Closed by zepto5** 2018-03-07 15:21 UTC
