### ISSUE TITLE
Form layout is different width ratio than ANC stage.

### ISSUE THREAD

**Issue by RahmanMonjur** [HRHR-project/e-registry-app#67] opened 2018-04-12 12:51 UTC
Form layout is different for Pregnancy Identification, Delivery Care (neonatal), PNC care (neonatal) stages than other stages. Its DEs label and controls width for value percentages are same as other DEs in other data entry forms (ANC).

**Comment by lukasewvd** [comment] 2018-04-16 10:36
This is not a bug, but done by design. Some program stages have been hard coded to look diffrent. For instance in dataentry-controller.js:
` if($scope.displayCustomForm === "COMPARE" && $scope.currentStage.id === 'FRSZV43y35y'){
      $scope.buildChildMenu(); }`

**Comment by lukasewvd** [comment] 2018-04-25 13:02
Should be fixed now.

**Closed by lukasewvd** 2018-04-25 13:02 UTC
